# -*- mode: ruby -*- 
# vi: set ft=ruby : 

Vagrant.configure("2") do |config|

        config.vm.define :cliente do |cliente|

                cliente.vm.box = "bento/ubuntu-22.04"
                cliente.vm.network :private_network, ip: "192.168.56.2"
                cliente.vm.hostname = "cliente"
        end

        config.vm.define :servidorE do |servidorE|

                servidorE.vm.box = "bento/ubuntu-22.04"
                servidorE.vm.network :private_network, ip: "192.168.56.3"
                servidorE.vm.hostname = "servidorEsclavo"
        end

        config.vm.define :servidorM do |servidorM|

                servidorM.vm.box = "bento/ubuntu-22.04"
                servidorM.vm.network :private_network, ip: "192.168.56.4"
                servidorM.vm.hostname = "servidorMaestro"
        end

        config.vm.provider "virtualbox" do |vb|

                vb.memory = "2048"
                vb.cpus = "4"
        end
end
