# -*- mode: ruby -*- 
# vi: set ft=ruby : 

Vagrant.configure("2") do |config|

        config.vm.define :servidor1 do |servidor1|

                servidor1.vm.box = "bento/ubuntu-22.04"
                servidor1.vm.network :private_network, ip: "192.168.56.2"
                servidor1.vm.hostname = "servidor1Prometheus"
                servidor1.vm.provision "shell", path: "scriptServidor1.sh"
        end

        config.vm.define :servidor2 do |servidor2|

                servidor2.vm.box = "bento/ubuntu-22.04"
                servidor2.vm.network :private_network, ip: "192.168.56.3"
                servidor2.vm.hostname = "servidor2Docker"
                servidor2.vm.provision "shell", path: "scriptServidor2.sh"
        end

        config.vm.provider "virtualbox" do |vb|

                vb.memory = "1024"
                vb.cpus = "2"
        end
end
